version: '3.9'

services:
  directus-db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: directus
  directus:
    image: ${REGISTRY_PREFIX:-}jaa-directus:latest
    environment:
      DB_CLIENT: pg
      DB_HOST: directus-db
      DB_PORT: 5432
      DB_DATABASE: directus
      DB_USER: directus
      ADMIN_EMAIL: admin@${PUBLIC_DOMAIN}
      CORS_ENABLED: 'true'

  chatwoot-db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: chatwoot
  chatwoot-cache:
    image: redis:7-alpine
  chatwoot-sidekiq:
    image: ${REGISTRY_PREFIX:-}jaa-chatwoot:latest
    environment:
      POSTGRES_HOST: chatwoot-db
      POSTGRES_USERNAME: chatwoot
      REDIS_URL: redis://chatwoot-cache:6379
      DISABLE_TELEMETRY: 'true'
    command: [bundle, exec, sidekiq, -C, config/sidekiq.yml]
  chatwoot-rails:
    image: ${REGISTRY_PREFIX:-}jaa-chatwoot:latest
    environment:
      POSTGRES_HOST: chatwoot-db
      POSTGRES_USERNAME: chatwoot
      REDIS_URL: redis://chatwoot-cache:6379
      ACTIVE_STORAGE_SERVICE: local
      ENABLE_ACCOUNT_SIGNUP: 'false'
      DISABLE_TELEMETRY: 'true'
    command:
      [
        'sh',
        '-c',
        'docker/entrypoints/rails.sh bundle exec rails db:chatwoot_prepare && docker/entrypoints/rails.sh bundle exec rails s -p 3000 -b 0.0.0.0',
      ]
