version: '3.9'

services:
  web:
    image: node:16-alpine
    volumes:
      - ./web:/usr/src/app
    working_dir: /usr/src/app
    environment:
      PUBLIC_DOMAIN: $PUBLIC_DOMAIN
    ports:
      - 3000:3000
    command: [sh, -c, 'npm ci && npm run dev']
    profiles:
      - web

  directus-db:
    environment:
      POSTGRES_PASSWORD: $DIRECTUS_DB_PASSWORD
  directus:
    build:
      context: directus
    depends_on:
      - directus-db
    ports:
      - 8055:8055
    volumes:
      - ./directus/snapshot.yaml:/directus/snapshot.yaml
      - ./directus/migrations:/directus/extensions/migrations
    environment:
      PUBLIC_URL: http://localhost:8055
      KEY: $DIRECTUS_KEY
      SECRET: $DIRECTUS_SECRET
      DB_PASSWORD: $DIRECTUS_DB_PASSWORD
      ADMIN_PASSWORD: $DIRECTUS_ADMIN_PASSWORD

  chatwoot-db:
    environment:
      POSTGRES_PASSWORD: $CHATWOOT_DB_PASSWORD
    profiles:
      - chatwoot
  chatwoot-cache:
    profiles:
      - chatwoot
  chatwoot-sidekiq:
    build:
      context: chatwoot
    depends_on:
      - chatwoot-db
      - chatwoot-cache
    environment:
      SECRET_KEY_BASE: $CHATWOOT_SECRET_KEY_BASE
      POSTGRES_PASSWORD: $CHATWOOT_DB_PASSWORD
    profiles:
      - chatwoot
  chatwoot-rails:
    build:
      context: chatwoot
    depends_on:
      - chatwoot-db
      - chatwoot-cache
    ports:
      - 3001:3000
    environment:
      FRONTEND_URL: http://localhost:3001
      SECRET_KEY_BASE: $CHATWOOT_SECRET_KEY_BASE
      POSTGRES_PASSWORD: $CHATWOOT_DB_PASSWORD
    profiles:
      - chatwoot
