version: '3.9'

services:
  directus-db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: directus
  directus:
    image: directus/directus:9.0.1
    environment:
      DB_CLIENT: pg
      DB_HOST: directus-db
      DB_PORT: 5432
      DB_DATABASE: directus
      DB_USER: directus
      ADMIN_EMAIL: admin@${PUBLIC_DOMAIN}

  chatwoot-db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: chatwoot
  chatwoot-cache:
    image: redis:6-alpine
  chatwoot-sidekiq:
    build:
      context: chatwoot
    image: jaa-chatwoot:latest
    environment:
      POSTGRES_HOST: chatwoot-db
      POSTGRES_USERNAME: chatwoot
      REDIS_URL: redis://chatwoot-cache:6379
      DISABLE_TELEMETRY: 'true'
    command: [bundle, exec, sidekiq, -C, config/sidekiq.yml]
  chatwoot-rails:
    build:
      context: chatwoot
    image: jaa-chatwoot:latest
    environment:
      POSTGRES_HOST: chatwoot-db
      POSTGRES_USERNAME: chatwoot
      REDIS_URL: redis://chatwoot-cache:6379
      ACTIVE_STORAGE_SERVICE: local
      ENABLE_ACCOUNT_SIGNUP: 'false'
      DEFAULT_LOCALE: de
      DISABLE_TELEMETRY: 'true'
    command: [sh, -c, 'docker/entrypoints/rails.sh bundle exec rails db:chatwoot_prepare && docker/entrypoints/rails.sh bundle exec rails s -p 3000 -b 0.0.0.0']
