version: '3.9'

x-logging: &default-logging
  driver: json-file
  options:
    max-size: 200k
    max-file: 10

services:
  web:
    build:
      context: web
    image: ${REGISTRY_PREFIX:-}jaa-web:latest
    init: true
    networks:
      - web
    environment:
      PUBLIC_DOMAIN: $PUBLIC_DOMAIN
    labels:
      traefik.enable: 'true'
      traefik.http.routers.jaa-web.rule: Host(`${PUBLIC_DOMAIN}`)
      traefik.http.routers.jaa-web.entrypoints: $TRAEFIK_ENTRYPOINTS
      traefik.http.routers.jaa-web.tls.certresolver: $TRAEFIK_CERTRESOLVER
    logging: *default-logging

  directus-db:
    volumes:
      - directus-db-data:/var/lib/postgresql/data
    secrets:
      - jaa_directus_db_password
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/jaa_directus_db_password
    networks:
      - jaa-directus
    logging: *default-logging
  directus-cache:
    image: redis:6-alpine
    networks:
      - jaa-directus
    logging: *default-logging
  directus:
    volumes:
      - directus-uploads:/directus/uploads
    secrets:
      - jaa_directus_key
      - jaa_directus_secret
      - jaa_directus_db_password
      - jaa_directus_admin_password
    environment:
      PUBLIC_URL: https://directus.${PUBLIC_DOMAIN}
      REFRESH_TOKEN_COOKIE_SECURE: 'true'
      DB_POOL_MIN: number:0
      CACHE_ENABLED: 'true'
      CACHE_STORE: redis
      CACHE_REDIS: redis://directus-cache:6379
      CACHE_AUTO_PURGE: 'true'
      KEY_FILE: /run/secrets/jaa_directus_key
      SECRET_FILE: /run/secrets/jaa_directus_secret
      DB_PASSWORD_FILE: /run/secrets/jaa_directus_db_password
      ADMIN_PASSWORD_FILE: /run/secrets/jaa_directus_admin_password
    networks:
      - jaa-directus
      - web
    labels:
      traefik.enable: 'true'
      traefik.http.routers.jaa-directus.rule: Host(`directus.${PUBLIC_DOMAIN}`)
      traefik.http.routers.jaa-directus.entrypoints: $TRAEFIK_ENTRYPOINTS
      traefik.http.routers.jaa-directus.tls.certresolver: $TRAEFIK_CERTRESOLVER
    logging: *default-logging

  chatwoot-db:
    volumes:
      - chatwoot-db-data:/var/lib/postgresql/data
    secrets:
      - jaa_chatwoot_db_password
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/jaa_chatwoot_db_password
    networks:
      - jaa-chatwoot
    logging: *default-logging
  chatwoot-cache:
    networks:
      - jaa-chatwoot
    logging: *default-logging
  chatwoot-sidekiq:
    image: ${REGISTRY_PREFIX:-}jaa-chatwoot:latest
    secrets:
      - jaa_chatwoot_secret_key_base
      - jaa_chatwoot_db_password
      - jaa_chatwoot_smtp_password
    environment:
      FRONTEND_URL: https://chatwoot.${PUBLIC_DOMAIN}
      SECRET_KEY_BASE_FILE: /run/secrets/jaa_chatwoot_secret_key_base
      POSTGRES_PASSWORD_FILE: /run/secrets/jaa_chatwoot_db_password
      MAILER_SENDER_EMAIL: $CHATWOOT_MAILER_SENDER_EMAIL
      SMTP_ADDRESS: $CHATWOOT_SMTP_ADDRESS
      SMTP_AUTHENTICATION: $CHATWOOT_SMTP_AUTHENTICATION
      SMTP_DOMAIN: $CHATWOOT_SMTP_DOMAIN
      SMTP_ENABLE_STARTTLS_AUTO: '$CHATWOOT_SMTP_ENABLE_STARTTLS_AUTO'
      SMTP_PORT: $CHATWOOT_SMTP_PORT
      SMTP_USERNAME: $CHATWOOT_SMTP_USERNAME
      SMTP_PASSWORD_FILE: /run/secrets/jaa_chatwoot_smtp_password
    networks:
      - default
      - jaa-chatwoot
    logging: *default-logging
  chatwoot-rails:
    image: ${REGISTRY_PREFIX:-}jaa-chatwoot:latest
    volumes:
      - chatwoot-rails-storage:/app/storage
    secrets:
      - jaa_chatwoot_secret_key_base
      - jaa_chatwoot_db_password
    environment:
      FRONTEND_URL: https://chatwoot.${PUBLIC_DOMAIN}
      FORCE_SSL: 'true'
      SECRET_KEY_BASE_FILE: /run/secrets/jaa_chatwoot_secret_key_base
      POSTGRES_PASSWORD_FILE: /run/secrets/jaa_chatwoot_db_password
    networks:
      - jaa-chatwoot
      - web
    labels:
      traefik.enable: 'true'
      traefik.http.routers.jaa-chatwoot.rule: Host(`chatwoot.${PUBLIC_DOMAIN}`)
      traefik.http.routers.jaa-chatwoot.entrypoints: $TRAEFIK_ENTRYPOINTS
      traefik.http.routers.jaa-chatwoot.tls.certresolver: $TRAEFIK_CERTRESOLVER
      traefik.http.routers.jaa-chatwoot.middlewares: chatwoot-headers
      traefik.http.middlewares.chatwoot-headers.headers.customrequestheaders.X-Forwarded-Proto: https
    logging: *default-logging

networks:
  web:
    name: $TRAEFIK_NETWORK
    external: true
  jaa-directus:
    internal: true
  jaa-chatwoot:
    internal: true

volumes:
  directus-db-data:
  directus-uploads:
  chatwoot-db-data:
  chatwoot-rails-storage:

secrets:
  jaa_directus_key:
    external: true
  jaa_directus_secret:
    external: true
  jaa_directus_db_password:
    external: true
  jaa_directus_admin_password:
    external: true
  jaa_chatwoot_secret_key_base:
    external: true
  jaa_chatwoot_db_password:
    external: true
  jaa_chatwoot_smtp_password:
    external: true
