version: '3.9'

services:
  directus-db:
    environment:
      POSTGRES_PASSWORD: $DIRECTUS_DB_PASSWORD
  directus:
    depends_on:
      - directus-db
    ports:
      - 8055:8055
    environment:
      PUBLIC_URL: http://localhost:8055
      KEY: $DIRECTUS_KEY
      SECRET: $DIRECTUS_SECRET
      DB_PASSWORD: $DIRECTUS_DB_PASSWORD
      ADMIN_PASSWORD: $DIRECTUS_ADMIN_PASSWORD

  chatwoot-db:
    environment:
      POSTGRES_PASSWORD: $CHATWOOT_DB_PASSWORD
  chatwoot-sidekiq:
    depends_on:
      - chatwoot-db
      - chatwoot-cache
    environment:
      SECRET_KEY_BASE: $CHATWOOT_SECRET_KEY_BASE
      POSTGRES_PASSWORD: $CHATWOOT_DB_PASSWORD
  chatwoot-rails:
    depends_on:
      - chatwoot-db
      - chatwoot-cache
    ports:
      - 3001:3000
    environment:
      FRONTEND_URL: http://localhost:3001
      SECRET_KEY_BASE: $CHATWOOT_SECRET_KEY_BASE
      POSTGRES_PASSWORD: $CHATWOOT_DB_PASSWORD
