name: Build Images

on:
  workflow_call:
    inputs:
      images:
        required: true
        type: string

jobs:
  build:
    if: inputs.images != '[]'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJSON(inputs.images) }}
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: {{defaultContext}}:${{ matrix.context }}
          push: ${{ github.ref_name == 'main' }}
          tags: paescuj/${{ matrix.name }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  result:
    name: Result
    if: inputs.images != '[]' && always()
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Mark result as failed
        if: needs.build.result != 'success'
        run: exit 1
