# Continuous Integration
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pre_check:
    name: Pre-Check
    continue-on-error: true
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.check_duplicate_workflows.outputs.should_skip }}
    steps:
      - name: Check duplicate workflows
        id: check_duplicate_workflows
        uses: fkirc/skip-duplicate-actions@master
        with:
          cancel_others: 'true'
          paths: '["web/**"]'

  lint:
    name: Lint
    needs: pre_check
    if: ${{ needs.pre_check.outputs.should_skip != 'true' }}
    uses: paescuj/jaa/.github/workflows/lint.yml@main

  test_build:
    name: Test Build
    needs: pre_check
    if: ${{ needs.pre_check.outputs.should_skip != 'true' }}
    uses: paescuj/jaa/.github/workflows/test-build.yml@main
