name: Test Build

on:
  push:
    branches:
      - main
    paths:
      - 'web/**'
  pull_request:
    branches:
      - main
    paths:
      - 'web/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: 'web/package-lock.json'
    - run: npm ci --prefix web
    - run: npm run --prefix web build
