name: Test Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pre:
    name: Pre Check
    continue-on-error: true
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          cancel_others: 'true'
          concurrent_skipping: 'same_content_newer'
          paths: '["web/**"]'
  lint:
    name: Test Build
    needs: pre
    if: ${{ needs.pre.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: 'web/package-lock.json'
      - run: |
          npm ci --prefix web
          npm run --prefix web build
